User Settings: bug and UI fixes & add connected accounts
inaturalist/inaturalist pull request #2886
Opened 2020-12-11 18:27 UTC by albullington

2020-12-12 00:19 UTC, kueda requested changes
Some other stuff that I couldn't add inline:

1. Let's change the licensing modal title to "About License Options." I think most of the text there needs improvement (e.g. CC0 is not actually a license), but I think I'll table that for later
1. Can we add the GBIF and Wikimedia badges to the license modal?

2020-12-12 00:44 UTC, albullington commented on app/webpack/users/edit/components/content.jsx
> +    const wikimedia = ["cc0", "cc-by", "cc-by-nc-sa"];
Per that list, should the Wikipedia tag be on `cc-by-sa` instead of `cc-by-nc-sa`?

2020-12-12 01:06 UTC, kueda commented on app/webpack/users/edit/components/content.jsx
> +    const wikimedia = ["cc0", "cc-by", "cc-by-nc-sa"];
Yeah, I think so. Good catch.

2020-12-16 20:35 UTC, albullington commented
@kueda I believe all the above changes are addressed in the latest commit. And I tried to clean up most of the classNames to better describe content vs. stylistic info.

2021-01-05 01:22 UTC, merged