Selectively validate on place bbox update
inaturalist/inaturalist pull request #3118
Opened 2021-07-07 02:46 UTC by todtb

Was thinking something like this for #2547 @kueda. 

I was assuming the skip validation was primarily around lat/lon, but let me know if you can think of another place where it would be conditional.

I played around with this in console and specs are green, but honestly must admit I don't have a great strategy here for manual testing.

2021-07-07 17:43 UTC, kueda requested changes
I suspect this will be fine without that one typo. And yeah, this one's hard to click test, so I think we just need to rely on the specs. In a way, it's encouraging that so many failed with that trailing comma.

2021-07-07 17:43 UTC, kueda commented on app/models/place.rb
> +        h[:longitude] = geom.centroid.x,
Trailing comma is causing `h[:longitude]` to be an array, which I think is the cause of all the spec failures. Behold the marvels of the Ruby interpreter: it has wonderful little gems like `tap` and truly horrific liabilities like this.

2021-07-07 23:00 UTC, todtb commented on app/models/place.rb
> -    calculate_bbox_area
This is handled by a before_save callback now that we aren't skipping.

2021-07-08 17:03 UTC, kueda approved these changes

2021-07-08 17:43 UTC, merged