first crack at app owner role
inaturalist/inaturalist pull request #3347
Opened 2022-01-05 00:51 UTC by loarie

closes #3339 but uses an approach analogous to curators (e.g. app_owner role, email application to grant role, and conditions (account older than 2 months, at least 10 improving ids for 4 weeks...) to be able to submit application

2022-01-05 21:25 UTC, loarie commented
@kueda after talking with tiwane and carrieseltzer rather than treat https://github.com/inaturalist/inaturalist/issues/3339 using a `privilege` I have it hear using a `role` very analogous to how we deal with curators:

1) users without the role don't see a link to create an application, rather to apply for the app owner role
<img width="1207" alt="Screen Shot 2022-01-05 at 1 15 25 PM" src="https://user-images.githubusercontent.com/598026/148290859-ac518586-6251-4e73-9b49-8bef961be10e.png">
If they don't have an account >2 months old and more than 10 IDs a week for the past 4 weeks, they can't submit an application:
<img width="845" alt="Screen Shot 2022-01-05 at 1 16 54 PM" src="https://user-images.githubusercontent.com/598026/148290930-8d2cb161-27d9-411e-849d-aef4906c194f.png">
Alternatively, they can submit the application which sends an email to help:
<img width="843" alt="Screen Shot 2022-01-05 at 1 08 50 PM" src="https://user-images.githubusercontent.com/598026/148290837-b22b5b57-dbe0-4402-84be-6b12826bdcad.png">
users/curate has tools to add that role:
<img width="422" alt="Screen Shot 2022-01-05 at 1 16 15 PM" src="https://user-images.githubusercontent.com/598026/148290900-ae511afd-991d-4af3-a4d1-36325fc3ed6c.png">
and remove that role:
<img width="435" alt="Screen Shot 2022-01-05 at 1 16 21 PM" src="https://user-images.githubusercontent.com/598026/148290909-fdfbe7f7-9c03-4088-914f-451dcb65d0e6.png">
and users with that role can create applications biz as usual
<img width="1205" alt="Screen Shot 2022-01-05 at 1 15 45 PM" src="https://user-images.githubusercontent.com/598026/148290879-b330c8a1-59c4-4d0d-bff1-74970036cd11.png">

Any thoughts on this approach before going into the details? I still want to test the email sending part of this which I haven't done but its rubocop and spec compliant

2022-01-06 16:42 UTC, kueda requested changes
Couple thoughts:

1. As mentioned, I think the current application requirement is too harsh and would recommend easing it to 10 improving IDs in the last month if the intent is to restrict API client use active, helpful users and not just superusers. If we remove manual approval maybe it could be a bit more harsh.
2. Adding manual approval is a big downer for client authors (it would certainly prevent me from ever making an iNat client), and it creates more work for Tony. Is Tony ok with this?
3. If we have manual approval, what are the requirements? The applicant should understand what is and is not acceptable functionality before they apply, both for clarity and to save Tony time, otherwise Tony is going to have to exchange multiple emails trying to understand things like what will be posted, how frequently, how auth info will be stored, etc.
4. You are implicitly grandparenting in all existing clients, so you might want to address that somewhere, maybe on the application page, e.g. "As of 2022 we are requiring manual approval for users wishing to make API clients"
5. Check all your translated text; I noted a few instances where you didn't actually update en.yml, but you should review them all.
6. Try walking through the entire application process locally including applying, approving, and rejecting to make sure everything works.

2022-01-06 16:42 UTC, kueda commented on config/locales/en.yml
> +    plan and we reserve the right to turn down applications for any reason.
Here's a re-write with American usage consistent with the rest of the default English text of the site (double quotes, terminal quote right of period, hyphenated adjectival phrases):

> In order to create third-party apps, you must first submit an application to become an "app owner." This application should describe the functionality your app will have and how you plan to use it. In order to submit an application your account must be at least 2 months old and must have made at least 10 improving identifications a week for each of the last 4 consecutive weeks. We may ask follow-up questions about your plan and we reserve the right to turn down applications for any reason.

2022-01-06 16:42 UTC, kueda commented on app/views/oauth_applications/app_owner_application.html.haml
> +  =t :apply_for_permissions_to_create_inat_third_party_applications_title
This text needs to be added to en.yml, or just use `apply_to_create_third_party_applications_title`

2022-01-06 16:42 UTC, kueda commented on app/controllers/oauth_applications_controller.rb
> +      flash[:notice] = t( :app_owner_application_success )
This translation is missing.

2022-01-06 16:42 UTC, kueda commented on app/controllers/oauth_applications_controller.rb
> +      flash[:notice] = I18n.t( :user_already_app_owner )
This translation is missing.

2022-01-06 16:42 UTC, kueda commented on app/views/users/curation.html.haml
> +          = link_to t(:make_app_owner), add_role_path(@display_user, :role => Role::APP_OWNER), :method => :post, class: "btn btn-block btn-success"
I'm pretty sure we don't use this view any more. I think you want to update https://github.com/inaturalist/inaturalist/blob/main/app/views/admin/user_detail.html.haml

2022-01-12 21:47 UTC, kueda requested changes
Still missing some translation keys, and some text needs to be updated. Also, how does the applicant get notified that their application was approved?

2022-01-13 22:51 UTC, merged