Add Identify keyboard shortcut to play observation's sound
inaturalist/inaturalist pull request #3562
Opened 2022-11-21 21:28 UTC by grfeller

[#3419](https://github.com/inaturalist/inaturalist/issues/3419)

Set focus to first `<audio>` element and play associated sound file. If an '<audio>' element is already active, the `togglePlayFirstSound` action exits early to avoid interfering with default processing.

2022-11-24 00:39 UTC, kueda requested changes
Works well in Firefox. In addition to the inline comments, here are some bugs / requests

- [ ] In Safari, SPACE will play the sound and focus on the player, but hitting SPACE again will not pause; seems like maybe SPACE does nothing while the player has focus, but only in Safari

I guess that was just one bug, singular. If you can find a workaround for Safari, great, but I think this is a step forward even if that seems impossible.

2022-11-24 00:39 UTC, kueda commented on app/webpack/observations/identify/components/observation_modal.jsx
> +      { keys: ["Space"], label: I18n.t( "play_first_sound" ) },
Please make "Space" all-caps to match the other named keys like SHIFT.

2022-11-24 00:39 UTC, kueda commented on app/webpack/observations/identify/actions/current_observation_actions.js
> +
Please abide by the eslint rules, at least for the code that you're adding. You can run `npx eslint --fix app/webpack/observations/identify/actions/current_observation_actions.js` if your editor doesn't automatically show you the eslint errors.

2022-12-03 19:56 UTC, grfeller commented
Firefox, Chromium and Safari should now behave as described (at least on macOS 12 and Ubuntu 20.04):
- SPACE will play the sound and focus on the *first* player. Hitting SPACE again will pause. 
- To avoid confusion, I removed the processing for subsequent `<audio>` elements; this makes the behavior *Play first sound* rather than *Play first / current sound* as previously implemented.

**Implementation**
- Binding to `keydown` instead of `keyup` suppressed the Firefox [shortcut for Toggle Play / Pause](https://support.mozilla.org/en-US/kb/keyboard-shortcuts-perform-firefox-tasks-quickly#w_media-shortcuts),

2022-12-07 19:44 UTC, kueda approved these changes

2022-12-07 19:45 UTC, merged

2022-12-07 19:45 UTC, kueda commented
Thanks, @grfeller! Sorry it took me a while to get back to this.

2022-12-08 16:06 UTC, grfeller commented
@kueda thanks for your help and feedback in making this PR successful.