#4184 show last edited observation field value
inaturalist/inaturalist pull request #4302
Opened 2024-12-01 00:35 UTC by jotamayo97

MERGE FIRST API PR
First time with Ruby, Im sorry if I made some mistake.
in observation_field_value.rb I expected to have to add 
`'belongs_to :updater, :class_name => 'User'`
I expected to collect this data from postgres but we r using elastic for this. Why?
Thanks for the feedback :)

2024-12-11 11:06 UTC, jotamayo97 commented
I noticed my PRs haven't received any feedback yet, and I see the project is quite active. I just wanted to check if there’s anything I need to adjust or improve :)

Thank you for your time and consideration!

2025-01-28 19:31 UTC, kueda requested changes
Thanks, @jotamayo97, this works for me, we just need a few small changes.

2025-01-28 19:31 UTC, kueda commented on app/webpack/observations/show/components/observation_field_value.jsx
> +          ) }
If you've got eslint running, it should be alerting you about indentation rules here. At a minimum, the contents of these outer divs should be indented.

2025-01-28 19:31 UTC, kueda commented on config/locales/en.yml
> +  last_edited_by: Last edited by
Please add a comment explaining to translators what this means and how it's used, e.g. "label for a field listing the name of the user who last edited a record"

2025-01-28 19:31 UTC, kueda commented on app/models/observation_field_value.rb
> +      updater_id: updater_id,
This works, but you should also describe this new field and its type around https://github.com/inaturalist/inaturalist/blob/main/app/es_indices/observation_index.rb#L180. This removes some guesswork on the part of elasticsearch and ensures this field is present if/when the index gets rebuilt. It also documents the entire shape of the schema for other developers.

2025-01-28 19:46 UTC, kueda commented
> I expected to collect this data from postgres but we r using elastic for this. Why?

You could fetch the data from postgres in the api like we're doing in `ObservationPreload.observerProjectMembership()` and similar methods, but your approach here works as well. Round trip to postgres adds some performance overhead, though, so your approach of adding fields to the ES index is probably better from that perspective. It also allows searching on that field if we ever want to do that.

2025-02-10 20:51 UTC, kueda commented
@jotamayo97 are you still planning on working on this? If not we can merge and make the changes I requested ourselves.

2025-02-18 16:14 UTC, jotamayo97 commented
Yeah sorry I will fix this ASAP :)
thanks for waiting for me!

2025-02-25 23:29 UTC, merged