Update old "Darwin Core Archives" link
inaturalist/inaturalist pull request #4303
Opened 2024-12-01 16:25 UTC by frewsxcv

The old link now redirects to this link

2025-01-28 19:54 UTC, kueda requested changes
Thanks for this, @frewsxcv, but this is going to result in existing translations existing translations getting unapproved without notifying translators. Also, of late, translators have been complaining about minor changes to large chunks of text like this, so if you're up to it, I think the ideal solution would be

- [ ] break this into multiple translatable strings that minimize markup, e.g. put the `p`, `ul`, and `li` tags in the react view and focus the translatable strings on the text
- [ ] take URLs out of the translations and pass them in as variables from the react views since they don't need to be localized

If you're not up for that, the second item and renaming the translation key to `other_options2_html` would be ok.

If you're not up for that either, totally fine, but please let us know so we can close.

2025-01-28 20:08 UTC, frewsxcv commented
It may take me a few days to get to it, but I think I have capacity to do all you mentioned, yeah. I'll let you know if not

2025-02-10 20:52 UTC, kueda commented
@frewsxcv still planning on working on this?

2025-02-10 21:36 UTC, frewsxcv commented
I unfortunately have limited capacity right now, so I won't be able to get to this anytime soon. So I'm going to close this. Thanks for taking a look

2025-02-10 21:36 UTC, closed without merging